### ISSUE TITLE
Difference with tqdm

### ISSUE THREAD

**Issue by sekhavatosan** [fastai/fast_progress#6]
Hi,

Thanks for your project. Would you please mention differences (implemented or planned) between fast_progress and [tqdm](https://pypi.python.org/pypi/tqdm) in README or somewhere?

**Comment by sgugger** [comment]
This is inspired by tqdm (obviously from the way the progress bars are designed) but we had some little problems by using tqdm (one with annoying vertical spaces when the nested bar disappeared, or others with multiprocess). 
This is very specific to a training loop (though they might be some other situations where people want to use something like this, which is why we shared), tqdm is far more general.
